// Code generated by protoc-gen-go.
// source: swagger.proto
// DO NOT EDIT!

package options

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Parameter_In int32

const (
	Parameter_QUERY  Parameter_In = 0
	Parameter_HEADER Parameter_In = 1
	Parameter_PATH   Parameter_In = 2
	Parameter_COOKIE Parameter_In = 3
)

var Parameter_In_name = map[int32]string{
	0: "QUERY",
	1: "HEADER",
	2: "PATH",
	3: "COOKIE",
}
var Parameter_In_value = map[string]int32{
	"QUERY":  0,
	"HEADER": 1,
	"PATH":   2,
	"COOKIE": 3,
}

func (x Parameter_In) String() string {
	return proto.EnumName(Parameter_In_name, int32(x))
}
func (Parameter_In) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{12, 0} }

type OpenAPI struct {
	Openapi      string                 `protobuf:"bytes,1,opt,name=openapi" json:"openapi,omitempty"`
	Info         *Info                  `protobuf:"bytes,2,opt,name=info" json:"info,omitempty"`
	Servers      []*Server              `protobuf:"bytes,4,rep,name=servers" json:"servers,omitempty"`
	Tags         []*Tag                 `protobuf:"bytes,5,rep,name=tags" json:"tags,omitempty"`
	Paths        map[string]*Path       `protobuf:"bytes,6,rep,name=paths" json:"paths,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Components   *Components            `protobuf:"bytes,7,opt,name=components" json:"components,omitempty"`
	ExternalDocs *ExternalDocumentation `protobuf:"bytes,8,opt,name=external_docs,json=externalDocs" json:"external_docs,omitempty"`
}

func (m *OpenAPI) Reset()                    { *m = OpenAPI{} }
func (m *OpenAPI) String() string            { return proto.CompactTextString(m) }
func (*OpenAPI) ProtoMessage()               {}
func (*OpenAPI) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *OpenAPI) GetOpenapi() string {
	if m != nil {
		return m.Openapi
	}
	return ""
}

func (m *OpenAPI) GetInfo() *Info {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *OpenAPI) GetServers() []*Server {
	if m != nil {
		return m.Servers
	}
	return nil
}

func (m *OpenAPI) GetTags() []*Tag {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *OpenAPI) GetPaths() map[string]*Path {
	if m != nil {
		return m.Paths
	}
	return nil
}

func (m *OpenAPI) GetComponents() *Components {
	if m != nil {
		return m.Components
	}
	return nil
}

func (m *OpenAPI) GetExternalDocs() *ExternalDocumentation {
	if m != nil {
		return m.ExternalDocs
	}
	return nil
}

type Info struct {
	Title          string   `protobuf:"bytes,1,opt,name=title" json:"title,omitempty"`
	Description    string   `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
	TermsOfService string   `protobuf:"bytes,3,opt,name=terms_of_service,json=termsOfService" json:"terms_of_service,omitempty"`
	Contact        *Contact `protobuf:"bytes,4,opt,name=contact" json:"contact,omitempty"`
	License        *License `protobuf:"bytes,5,opt,name=license" json:"license,omitempty"`
	Version        string   `protobuf:"bytes,6,opt,name=version" json:"version,omitempty"`
}

func (m *Info) Reset()                    { *m = Info{} }
func (m *Info) String() string            { return proto.CompactTextString(m) }
func (*Info) ProtoMessage()               {}
func (*Info) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *Info) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Info) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Info) GetTermsOfService() string {
	if m != nil {
		return m.TermsOfService
	}
	return ""
}

func (m *Info) GetContact() *Contact {
	if m != nil {
		return m.Contact
	}
	return nil
}

func (m *Info) GetLicense() *License {
	if m != nil {
		return m.License
	}
	return nil
}

func (m *Info) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type Contact struct {
	Name  string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Url   string `protobuf:"bytes,2,opt,name=url" json:"url,omitempty"`
	Email string `protobuf:"bytes,3,opt,name=email" json:"email,omitempty"`
}

func (m *Contact) Reset()                    { *m = Contact{} }
func (m *Contact) String() string            { return proto.CompactTextString(m) }
func (*Contact) ProtoMessage()               {}
func (*Contact) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *Contact) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Contact) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Contact) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type License struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Url  string `protobuf:"bytes,2,opt,name=url" json:"url,omitempty"`
}

func (m *License) Reset()                    { *m = License{} }
func (m *License) String() string            { return proto.CompactTextString(m) }
func (*License) ProtoMessage()               {}
func (*License) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *License) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *License) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type Server struct {
	Url         string                     `protobuf:"bytes,1,opt,name=url" json:"url,omitempty"`
	Description string                     `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
	Variables   map[string]*ServerVariable `protobuf:"bytes,3,rep,name=variables" json:"variables,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *Server) Reset()                    { *m = Server{} }
func (m *Server) String() string            { return proto.CompactTextString(m) }
func (*Server) ProtoMessage()               {}
func (*Server) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

func (m *Server) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Server) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Server) GetVariables() map[string]*ServerVariable {
	if m != nil {
		return m.Variables
	}
	return nil
}

type ServerVariable struct {
	Enum        []string `protobuf:"bytes,1,rep,name=enum" json:"enum,omitempty"`
	Default     string   `protobuf:"bytes,2,opt,name=default" json:"default,omitempty"`
	Description string   `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
}

func (m *ServerVariable) Reset()                    { *m = ServerVariable{} }
func (m *ServerVariable) String() string            { return proto.CompactTextString(m) }
func (*ServerVariable) ProtoMessage()               {}
func (*ServerVariable) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

func (m *ServerVariable) GetEnum() []string {
	if m != nil {
		return m.Enum
	}
	return nil
}

func (m *ServerVariable) GetDefault() string {
	if m != nil {
		return m.Default
	}
	return ""
}

func (m *ServerVariable) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type Tag struct {
	Name         string                 `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Description  string                 `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
	ExternalDocs *ExternalDocumentation `protobuf:"bytes,3,opt,name=external_docs,json=externalDocs" json:"external_docs,omitempty"`
}

func (m *Tag) Reset()                    { *m = Tag{} }
func (m *Tag) String() string            { return proto.CompactTextString(m) }
func (*Tag) ProtoMessage()               {}
func (*Tag) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{6} }

func (m *Tag) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Tag) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Tag) GetExternalDocs() *ExternalDocumentation {
	if m != nil {
		return m.ExternalDocs
	}
	return nil
}

type ExternalDocumentation struct {
	Url         string `protobuf:"bytes,1,opt,name=url" json:"url,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
}

func (m *ExternalDocumentation) Reset()                    { *m = ExternalDocumentation{} }
func (m *ExternalDocumentation) String() string            { return proto.CompactTextString(m) }
func (*ExternalDocumentation) ProtoMessage()               {}
func (*ExternalDocumentation) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{7} }

func (m *ExternalDocumentation) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *ExternalDocumentation) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type Path struct {
	Summary     string     `protobuf:"bytes,1,opt,name=summary" json:"summary,omitempty"`
	Description string     `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
	Delete      *Operation `protobuf:"bytes,3,opt,name=delete" json:"delete,omitempty"`
	Get         *Operation `protobuf:"bytes,4,opt,name=get" json:"get,omitempty"`
	Head        *Operation `protobuf:"bytes,5,opt,name=head" json:"head,omitempty"`
	Options     *Operation `protobuf:"bytes,6,opt,name=options" json:"options,omitempty"`
	Patch       *Operation `protobuf:"bytes,7,opt,name=patch" json:"patch,omitempty"`
	Post        *Operation `protobuf:"bytes,8,opt,name=post" json:"post,omitempty"`
	Put         *Operation `protobuf:"bytes,9,opt,name=put" json:"put,omitempty"`
	Trace       *Operation `protobuf:"bytes,10,opt,name=trace" json:"trace,omitempty"`
}

func (m *Path) Reset()                    { *m = Path{} }
func (m *Path) String() string            { return proto.CompactTextString(m) }
func (*Path) ProtoMessage()               {}
func (*Path) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{8} }

func (m *Path) GetSummary() string {
	if m != nil {
		return m.Summary
	}
	return ""
}

func (m *Path) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Path) GetDelete() *Operation {
	if m != nil {
		return m.Delete
	}
	return nil
}

func (m *Path) GetGet() *Operation {
	if m != nil {
		return m.Get
	}
	return nil
}

func (m *Path) GetHead() *Operation {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *Path) GetOptions() *Operation {
	if m != nil {
		return m.Options
	}
	return nil
}

func (m *Path) GetPatch() *Operation {
	if m != nil {
		return m.Patch
	}
	return nil
}

func (m *Path) GetPost() *Operation {
	if m != nil {
		return m.Post
	}
	return nil
}

func (m *Path) GetPut() *Operation {
	if m != nil {
		return m.Put
	}
	return nil
}

func (m *Path) GetTrace() *Operation {
	if m != nil {
		return m.Trace
	}
	return nil
}

type Operation struct {
	Tags         []string               `protobuf:"bytes,1,rep,name=tags" json:"tags,omitempty"`
	Summary      string                 `protobuf:"bytes,2,opt,name=summary" json:"summary,omitempty"`
	Description  string                 `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
	ExternalDocs *ExternalDocumentation `protobuf:"bytes,4,opt,name=external_docs,json=externalDocs" json:"external_docs,omitempty"`
	OperationId  string                 `protobuf:"bytes,5,opt,name=operation_id,json=operationId" json:"operation_id,omitempty"`
	Parameters   []*Parameter           `protobuf:"bytes,6,rep,name=parameters" json:"parameters,omitempty"`
	RequestBody  *RequestBody           `protobuf:"bytes,7,opt,name=request_body,json=requestBody" json:"request_body,omitempty"`
	Responses    map[string]*Response   `protobuf:"bytes,8,rep,name=responses" json:"responses,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Deprecated   bool                   `protobuf:"varint,10,opt,name=deprecated" json:"deprecated,omitempty"`
}

func (m *Operation) Reset()                    { *m = Operation{} }
func (m *Operation) String() string            { return proto.CompactTextString(m) }
func (*Operation) ProtoMessage()               {}
func (*Operation) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{9} }

func (m *Operation) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *Operation) GetSummary() string {
	if m != nil {
		return m.Summary
	}
	return ""
}

func (m *Operation) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Operation) GetExternalDocs() *ExternalDocumentation {
	if m != nil {
		return m.ExternalDocs
	}
	return nil
}

func (m *Operation) GetOperationId() string {
	if m != nil {
		return m.OperationId
	}
	return ""
}

func (m *Operation) GetParameters() []*Parameter {
	if m != nil {
		return m.Parameters
	}
	return nil
}

func (m *Operation) GetRequestBody() *RequestBody {
	if m != nil {
		return m.RequestBody
	}
	return nil
}

func (m *Operation) GetResponses() map[string]*Response {
	if m != nil {
		return m.Responses
	}
	return nil
}

func (m *Operation) GetDeprecated() bool {
	if m != nil {
		return m.Deprecated
	}
	return false
}

type Components struct {
	Schemas map[string]*Schema `protobuf:"bytes,1,rep,name=schemas" json:"schemas,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *Components) Reset()                    { *m = Components{} }
func (m *Components) String() string            { return proto.CompactTextString(m) }
func (*Components) ProtoMessage()               {}
func (*Components) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{10} }

func (m *Components) GetSchemas() map[string]*Schema {
	if m != nil {
		return m.Schemas
	}
	return nil
}

type Schema struct {
	Description string             `protobuf:"bytes,1,opt,name=description" json:"description,omitempty"`
	Type        string             `protobuf:"bytes,2,opt,name=type" json:"type,omitempty"`
	Properties  map[string]*Schema `protobuf:"bytes,3,rep,name=properties" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Required    []string           `protobuf:"bytes,4,rep,name=required" json:"required,omitempty"`
	Format      string             `protobuf:"bytes,5,opt,name=format" json:"format,omitempty"`
	Ref         string             `protobuf:"bytes,6,opt,name=ref" json:"ref,omitempty"`
}

func (m *Schema) Reset()                    { *m = Schema{} }
func (m *Schema) String() string            { return proto.CompactTextString(m) }
func (*Schema) ProtoMessage()               {}
func (*Schema) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{11} }

func (m *Schema) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Schema) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Schema) GetProperties() map[string]*Schema {
	if m != nil {
		return m.Properties
	}
	return nil
}

func (m *Schema) GetRequired() []string {
	if m != nil {
		return m.Required
	}
	return nil
}

func (m *Schema) GetFormat() string {
	if m != nil {
		return m.Format
	}
	return ""
}

func (m *Schema) GetRef() string {
	if m != nil {
		return m.Ref
	}
	return ""
}

type Parameter struct {
	Name            string       `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	In              Parameter_In `protobuf:"varint,2,opt,name=in,enum=com.pseudomuto.protoc_gen_twagger.options.Parameter_In" json:"in,omitempty"`
	Description     string       `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
	Required        bool         `protobuf:"varint,4,opt,name=required" json:"required,omitempty"`
	AllowEmptyValue bool         `protobuf:"varint,5,opt,name=allow_empty_value,json=allowEmptyValue" json:"allow_empty_value,omitempty"`
}

func (m *Parameter) Reset()                    { *m = Parameter{} }
func (m *Parameter) String() string            { return proto.CompactTextString(m) }
func (*Parameter) ProtoMessage()               {}
func (*Parameter) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{12} }

func (m *Parameter) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Parameter) GetIn() Parameter_In {
	if m != nil {
		return m.In
	}
	return Parameter_QUERY
}

func (m *Parameter) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Parameter) GetRequired() bool {
	if m != nil {
		return m.Required
	}
	return false
}

func (m *Parameter) GetAllowEmptyValue() bool {
	if m != nil {
		return m.AllowEmptyValue
	}
	return false
}

type RequestBody struct {
	Description string                `protobuf:"bytes,1,opt,name=description" json:"description,omitempty"`
	Content     map[string]*MediaType `protobuf:"bytes,2,rep,name=content" json:"content,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Required    bool                  `protobuf:"varint,3,opt,name=required" json:"required,omitempty"`
}

func (m *RequestBody) Reset()                    { *m = RequestBody{} }
func (m *RequestBody) String() string            { return proto.CompactTextString(m) }
func (*RequestBody) ProtoMessage()               {}
func (*RequestBody) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{13} }

func (m *RequestBody) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *RequestBody) GetContent() map[string]*MediaType {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *RequestBody) GetRequired() bool {
	if m != nil {
		return m.Required
	}
	return false
}

type Response struct {
	Description string                `protobuf:"bytes,1,opt,name=description" json:"description,omitempty"`
	Content     map[string]*MediaType `protobuf:"bytes,3,rep,name=content" json:"content,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{14} }

func (m *Response) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Response) GetContent() map[string]*MediaType {
	if m != nil {
		return m.Content
	}
	return nil
}

type MediaType struct {
	Schema *Schema `protobuf:"bytes,1,opt,name=schema" json:"schema,omitempty"`
}

func (m *MediaType) Reset()                    { *m = MediaType{} }
func (m *MediaType) String() string            { return proto.CompactTextString(m) }
func (*MediaType) ProtoMessage()               {}
func (*MediaType) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{15} }

func (m *MediaType) GetSchema() *Schema {
	if m != nil {
		return m.Schema
	}
	return nil
}

func init() {
	proto.RegisterType((*OpenAPI)(nil), "com.pseudomuto.protoc_gen_twagger.options.OpenAPI")
	proto.RegisterType((*Info)(nil), "com.pseudomuto.protoc_gen_twagger.options.Info")
	proto.RegisterType((*Contact)(nil), "com.pseudomuto.protoc_gen_twagger.options.Contact")
	proto.RegisterType((*License)(nil), "com.pseudomuto.protoc_gen_twagger.options.License")
	proto.RegisterType((*Server)(nil), "com.pseudomuto.protoc_gen_twagger.options.Server")
	proto.RegisterType((*ServerVariable)(nil), "com.pseudomuto.protoc_gen_twagger.options.ServerVariable")
	proto.RegisterType((*Tag)(nil), "com.pseudomuto.protoc_gen_twagger.options.Tag")
	proto.RegisterType((*ExternalDocumentation)(nil), "com.pseudomuto.protoc_gen_twagger.options.ExternalDocumentation")
	proto.RegisterType((*Path)(nil), "com.pseudomuto.protoc_gen_twagger.options.Path")
	proto.RegisterType((*Operation)(nil), "com.pseudomuto.protoc_gen_twagger.options.Operation")
	proto.RegisterType((*Components)(nil), "com.pseudomuto.protoc_gen_twagger.options.Components")
	proto.RegisterType((*Schema)(nil), "com.pseudomuto.protoc_gen_twagger.options.Schema")
	proto.RegisterType((*Parameter)(nil), "com.pseudomuto.protoc_gen_twagger.options.Parameter")
	proto.RegisterType((*RequestBody)(nil), "com.pseudomuto.protoc_gen_twagger.options.RequestBody")
	proto.RegisterType((*Response)(nil), "com.pseudomuto.protoc_gen_twagger.options.Response")
	proto.RegisterType((*MediaType)(nil), "com.pseudomuto.protoc_gen_twagger.options.MediaType")
	proto.RegisterEnum("com.pseudomuto.protoc_gen_twagger.options.Parameter_In", Parameter_In_name, Parameter_In_value)
}

func init() { proto.RegisterFile("swagger.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 1227 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xbc, 0x57, 0x4b, 0x6f, 0xdb, 0x46,
	0x10, 0xae, 0x48, 0xea, 0xc1, 0x91, 0xe2, 0xb0, 0x8b, 0xb6, 0x20, 0x74, 0x28, 0x5c, 0x9e, 0xdc,
	0x1e, 0x14, 0xc4, 0x49, 0x9f, 0x40, 0x81, 0xd8, 0x8e, 0x9a, 0x48, 0x71, 0x6b, 0x97, 0x76, 0x02,
	0x24, 0x68, 0xab, 0xae, 0xc9, 0x91, 0x4c, 0x54, 0x7c, 0x84, 0x5c, 0xd9, 0xd5, 0x0f, 0x68, 0xff,
	0x41, 0x6f, 0x41, 0x0e, 0xfd, 0x57, 0xf9, 0x31, 0x05, 0x8a, 0x7d, 0x50, 0x22, 0x6d, 0xa1, 0x11,
	0x15, 0xb8, 0xb7, 0xdd, 0xd9, 0x9d, 0x6f, 0x38, 0xdf, 0xce, 0x8b, 0x70, 0x2b, 0xbb, 0xa4, 0x93,
	0x09, 0xa6, 0xbd, 0x24, 0x8d, 0x59, 0x4c, 0x3e, 0xf5, 0xe2, 0xb0, 0x97, 0x64, 0x38, 0xf3, 0xe3,
	0x70, 0xc6, 0x62, 0x29, 0xf5, 0x46, 0x13, 0x8c, 0x46, 0x4c, 0x5d, 0x8c, 0x13, 0x16, 0xc4, 0x51,
	0xe6, 0xfc, 0x63, 0x40, 0xf3, 0x28, 0xc1, 0x68, 0xef, 0x78, 0x40, 0x6c, 0x68, 0xc6, 0x09, 0x46,
	0x34, 0x09, 0xec, 0xda, 0x76, 0x6d, 0xc7, 0x74, 0xf3, 0x2d, 0x39, 0x00, 0x23, 0x88, 0xc6, 0xb1,
	0xad, 0x6d, 0xd7, 0x76, 0xda, 0xbb, 0x77, 0x7a, 0x6b, 0xe3, 0xf7, 0x06, 0xd1, 0x38, 0x76, 0x85,
	0x32, 0x79, 0x02, 0xcd, 0x0c, 0xd3, 0x0b, 0x4c, 0x33, 0xdb, 0xd8, 0xd6, 0x77, 0xda, 0xbb, 0x77,
	0x2b, 0xe0, 0x9c, 0x08, 0x4d, 0x37, 0x47, 0x20, 0xfb, 0x60, 0x30, 0x3a, 0xc9, 0xec, 0xba, 0x40,
	0xea, 0x55, 0x40, 0x3a, 0xa5, 0x13, 0x57, 0xe8, 0x92, 0x13, 0xa8, 0x27, 0x94, 0x9d, 0x67, 0x76,
	0x43, 0x80, 0x7c, 0x5b, 0x01, 0x44, 0x51, 0xd6, 0x3b, 0xe6, 0xfa, 0xfd, 0x88, 0xa5, 0x73, 0x57,
	0x62, 0x91, 0xa7, 0x00, 0x5e, 0x1c, 0x26, 0x71, 0x84, 0x11, 0xcb, 0xec, 0xa6, 0x20, 0xec, 0xf3,
	0x0a, 0xc8, 0x07, 0x0b, 0x65, 0xb7, 0x00, 0x44, 0x10, 0x6e, 0xe1, 0xef, 0x0c, 0xd3, 0x88, 0x4e,
	0x47, 0x7e, 0xec, 0x65, 0x76, 0x4b, 0x20, 0x3f, 0xa8, 0x80, 0xdc, 0x57, 0xfa, 0x0f, 0x63, 0x6f,
	0x16, 0x62, 0xc4, 0x28, 0x17, 0xbb, 0x1d, 0x5c, 0x8a, 0xb3, 0x6e, 0x00, 0xb0, 0x74, 0x89, 0x58,
	0xa0, 0xff, 0x86, 0x73, 0x15, 0x0c, 0x7c, 0x49, 0xfa, 0x50, 0xbf, 0xa0, 0xd3, 0x19, 0x6e, 0x10,
	0x09, 0x1c, 0xd7, 0x95, 0xda, 0xdf, 0x68, 0x5f, 0xd5, 0x86, 0x46, 0x4b, 0xb7, 0x0c, 0xe7, 0xb5,
	0x06, 0x06, 0x8f, 0x11, 0xf2, 0x01, 0xd4, 0x59, 0xc0, 0xa6, 0xa8, 0xac, 0xc9, 0x0d, 0xd9, 0x86,
	0xb6, 0x8f, 0x99, 0x97, 0x06, 0x02, 0x44, 0x58, 0x35, 0xdd, 0xa2, 0x88, 0xec, 0x80, 0xc5, 0x30,
	0x0d, 0xb3, 0x51, 0x3c, 0x1e, 0xf1, 0xe0, 0x08, 0x3c, 0xb4, 0x75, 0x71, 0x6d, 0x4b, 0xc8, 0x8f,
	0xc6, 0x27, 0x52, 0x4a, 0x0e, 0xa1, 0xe9, 0xc5, 0x11, 0xa3, 0x1e, 0xb3, 0x0d, 0xf1, 0xf5, 0xbb,
	0x95, 0x9e, 0x45, 0x68, 0xba, 0x39, 0x04, 0x47, 0x9b, 0x06, 0x1e, 0x46, 0x19, 0xda, 0xf5, 0xca,
	0x68, 0x87, 0x52, 0xd3, 0xcd, 0x21, 0x78, 0xea, 0xf1, 0xb0, 0xe6, 0x3e, 0x36, 0x64, 0xea, 0xa9,
	0xad, 0xd3, 0x87, 0xa6, 0xb2, 0x4d, 0x08, 0x18, 0x11, 0x0d, 0x73, 0x86, 0xc4, 0x9a, 0x3f, 0xd1,
	0x2c, 0x9d, 0x2a, 0x62, 0xf8, 0x92, 0x13, 0x89, 0x21, 0x0d, 0xa6, 0x8a, 0x05, 0xb9, 0x71, 0xee,
	0x40, 0x53, 0x19, 0x5d, 0x0f, 0xc6, 0xf9, 0x4b, 0x83, 0x86, 0x4c, 0xba, 0xfc, 0xb0, 0xb6, 0xb4,
	0xf1, 0xf6, 0x67, 0xf9, 0x05, 0xcc, 0x0b, 0x9a, 0x06, 0xf4, 0x6c, 0x8a, 0x99, 0xad, 0x8b, 0xfc,
	0x7a, 0x50, 0x39, 0xdd, 0x7b, 0xcf, 0x72, 0x08, 0x99, 0x62, 0x4b, 0xc8, 0xee, 0x25, 0x6c, 0x95,
	0x0f, 0x57, 0x04, 0xeb, 0x51, 0x39, 0x58, 0xbf, 0xae, 0x6c, 0x3f, 0xb7, 0x50, 0x08, 0x5b, 0xe7,
	0x57, 0xd8, 0x2a, 0x1f, 0x72, 0x3e, 0x31, 0x9a, 0x85, 0x76, 0x6d, 0x5b, 0xe7, 0x7c, 0xf2, 0x35,
	0x7f, 0x4f, 0x1f, 0xc7, 0x74, 0x36, 0x65, 0x8a, 0x9c, 0x7c, 0x7b, 0x95, 0x3a, 0xfd, 0x1a, 0x75,
	0xce, 0xdf, 0x35, 0xd0, 0x4f, 0xe9, 0x64, 0xe5, 0x3b, 0xbd, 0x9d, 0xf8, 0x6b, 0x85, 0x42, 0xbf,
	0x89, 0x42, 0xe1, 0x3c, 0x81, 0x0f, 0x57, 0x5e, 0xdb, 0x24, 0x58, 0x9c, 0x57, 0x75, 0x30, 0x78,
	0x79, 0xe0, 0xb4, 0x65, 0xb3, 0x30, 0xa4, 0x69, 0xfe, 0x8e, 0xf9, 0x76, 0x0d, 0xc7, 0x0f, 0xa1,
	0xe1, 0xe3, 0x14, 0x19, 0x2a, 0x8f, 0xef, 0x57, 0x2b, 0xe7, 0xa9, 0xf4, 0x52, 0x61, 0x90, 0xef,
	0x40, 0x9f, 0x60, 0x5e, 0x28, 0x36, 0x83, 0xe2, 0x00, 0xe4, 0x31, 0x18, 0xe7, 0x48, 0x7d, 0x55,
	0x23, 0x36, 0x03, 0x12, 0x08, 0xe4, 0x07, 0xde, 0x9d, 0xc5, 0x91, 0x28, 0x11, 0x9b, 0x82, 0xe5,
	0x20, 0x64, 0x28, 0xba, 0x9f, 0x77, 0xae, 0x7a, 0xd4, 0x66, 0x68, 0x12, 0x82, 0x7b, 0x99, 0xc4,
	0x19, 0x53, 0x4d, 0x69, 0x43, 0x2f, 0x39, 0x02, 0xe7, 0x3d, 0x99, 0x31, 0xdb, 0x7c, 0x17, 0xde,
	0x93, 0x19, 0xe3, 0xde, 0xb1, 0x94, 0x7a, 0x68, 0xc3, 0xbb, 0x78, 0x27, 0x20, 0x9c, 0xd7, 0x75,
	0x30, 0x17, 0x42, 0x9e, 0x96, 0x62, 0xf2, 0x50, 0xe9, 0x2e, 0x26, 0x89, 0x42, 0xdc, 0x6a, 0xff,
	0x19, 0xb7, 0xfa, 0x1a, 0x09, 0x6b, 0xdc, 0x44, 0xc2, 0x92, 0x4f, 0xa0, 0x13, 0xe7, 0x3e, 0x8c,
	0x02, 0x19, 0x90, 0xa6, 0xdb, 0x5e, 0xc8, 0x06, 0x3e, 0x39, 0x05, 0x48, 0x68, 0x4a, 0x43, 0x64,
	0x7c, 0x46, 0x93, 0x43, 0xd1, 0xfd, 0x4a, 0x1d, 0x5e, 0x29, 0xbb, 0x05, 0x1c, 0xf2, 0x1c, 0x3a,
	0x29, 0xbe, 0x9c, 0x61, 0xc6, 0x46, 0x67, 0xb1, 0x3f, 0x57, 0xe1, 0xf6, 0x45, 0x05, 0x5c, 0x57,
	0xaa, 0xef, 0xc7, 0xfe, 0xdc, 0x6d, 0xa7, 0xcb, 0x0d, 0xa1, 0x60, 0xa6, 0x98, 0x25, 0x71, 0x94,
	0x21, 0x1f, 0x88, 0xf8, 0xf7, 0x1e, 0x6c, 0xf2, 0xd0, 0x3d, 0x37, 0x47, 0x51, 0x7d, 0x66, 0x81,
	0x4a, 0x3e, 0x06, 0xf0, 0x31, 0x49, 0xd1, 0xa3, 0x0c, 0x7d, 0x11, 0x4c, 0x2d, 0xb7, 0x20, 0xe9,
	0xbe, 0x84, 0xad, 0xb2, 0xf2, 0x8a, 0x3e, 0x34, 0x28, 0xf7, 0xa1, 0x7b, 0x95, 0x5c, 0x97, 0xd8,
	0xe5, 0xc1, 0xc9, 0xb4, 0x60, 0x68, 0xb4, 0xda, 0x56, 0x67, 0x68, 0xb4, 0x3a, 0xd6, 0x2d, 0xe7,
	0x4d, 0x0d, 0x60, 0x39, 0x37, 0x92, 0x9f, 0xa0, 0x99, 0x79, 0xe7, 0x18, 0x52, 0x19, 0xa4, 0xed,
	0xdd, 0xfd, 0x8d, 0xe6, 0xcf, 0xde, 0x89, 0x04, 0x91, 0x9c, 0xe4, 0x90, 0xdd, 0x10, 0x3a, 0xc5,
	0x83, 0x15, 0xfe, 0x3e, 0x2a, 0xfb, 0x5b, 0x69, 0xcc, 0x17, 0xc8, 0xc5, 0x7e, 0xfb, 0x86, 0xcf,
	0x21, 0x42, 0x7a, 0x35, 0x97, 0x6a, 0xd7, 0x73, 0x89, 0xe7, 0xe6, 0x3c, 0x41, 0x95, 0x84, 0x62,
	0x4d, 0x28, 0x40, 0x92, 0xf2, 0x30, 0x67, 0xc1, 0x62, 0x14, 0xd9, 0xab, 0xfc, 0x49, 0xbd, 0xe3,
	0x05, 0x86, 0xe4, 0xa3, 0x00, 0x4a, 0xba, 0xd0, 0xe2, 0x61, 0x19, 0xa4, 0xe8, 0x8b, 0x5f, 0x1b,
	0xd3, 0x5d, 0xec, 0xc9, 0x47, 0xd0, 0x18, 0xc7, 0x69, 0x48, 0x99, 0xca, 0x38, 0xb5, 0xe3, 0xb4,
	0xa5, 0x38, 0x56, 0xd3, 0x1e, 0x5f, 0x76, 0x13, 0xb8, 0x7d, 0xc5, 0xc8, 0x4d, 0x73, 0xfb, 0x87,
	0x06, 0xe6, 0x22, 0x69, 0x57, 0xce, 0x1b, 0x8f, 0x40, 0x0b, 0x64, 0xb7, 0xdd, 0xda, 0xfd, 0x72,
	0x93, 0x52, 0xd0, 0x1b, 0x44, 0xae, 0x16, 0x44, 0x6b, 0xd4, 0xc1, 0x32, 0x89, 0x3c, 0xcf, 0x96,
	0x24, 0x7e, 0x06, 0xef, 0xd3, 0xe9, 0x34, 0xbe, 0x1c, 0x61, 0x98, 0xb0, 0xf9, 0x48, 0x32, 0x50,
	0x17, 0x97, 0x6e, 0x8b, 0x83, 0x3e, 0x97, 0x3f, 0xe3, 0x62, 0xe7, 0x2e, 0x68, 0x83, 0x88, 0x98,
	0x50, 0xff, 0xf1, 0x69, 0xdf, 0x7d, 0x6e, 0xbd, 0x47, 0x00, 0x1a, 0x8f, 0xfb, 0x7b, 0x0f, 0xfb,
	0xae, 0x55, 0x23, 0x2d, 0x30, 0x8e, 0xf7, 0x4e, 0x1f, 0x5b, 0x1a, 0x97, 0x1e, 0x1c, 0x1d, 0x3d,
	0x19, 0xf4, 0x2d, 0xdd, 0x79, 0xa5, 0x41, 0xbb, 0x50, 0x64, 0xd6, 0x08, 0xb4, 0x9f, 0xe5, 0xbf,
	0x04, 0x46, 0x7c, 0xbe, 0xab, 0x5a, 0x77, 0x0a, 0xa6, 0xc4, 0x7f, 0x05, 0x46, 0x4c, 0xe5, 0x98,
	0xc2, 0x2c, 0x71, 0xa1, 0x97, 0xb9, 0xe8, 0x26, 0xd0, 0x29, 0x2a, 0xad, 0x88, 0x91, 0x61, 0x39,
	0x46, 0xaa, 0x94, 0xf0, 0xef, 0xd1, 0x0f, 0xe8, 0xe9, 0x3c, 0x29, 0x8d, 0xbc, 0x7f, 0x6a, 0xd0,
	0xca, 0x0b, 0xd1, 0x1a, 0xdc, 0xbc, 0x58, 0x72, 0x53, 0x7d, 0xf0, 0xcf, 0xed, 0xac, 0x26, 0xe6,
	0xff, 0x77, 0x7e, 0x68, 0xb4, 0x34, 0x4b, 0x1f, 0x1a, 0x2d, 0xc3, 0xaa, 0x3b, 0xe7, 0x60, 0x2e,
	0xee, 0x90, 0x01, 0x34, 0x64, 0x49, 0x14, 0xd6, 0x37, 0x4a, 0x45, 0x05, 0xb0, 0xb0, 0xa1, 0x5b,
	0x86, 0xb4, 0xb4, 0x6f, 0xbe, 0xc8, 0xe7, 0xb4, 0xb3, 0x86, 0xc0, 0xb9, 0xf7, 0x6f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xa0, 0x9f, 0x57, 0x09, 0xe4, 0x11, 0x00, 0x00,
}
