// Code generated by protoc-gen-go.
// source: swagger.proto
// DO NOT EDIT!

package options

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type OpenAPI struct {
	Openapi      string                 `protobuf:"bytes,1,opt,name=openapi" json:"openapi,omitempty"`
	Info         *Info                  `protobuf:"bytes,2,opt,name=info" json:"info,omitempty"`
	Servers      []*Server              `protobuf:"bytes,4,rep,name=servers" json:"servers,omitempty"`
	Tags         []*Tag                 `protobuf:"bytes,5,rep,name=tags" json:"tags,omitempty"`
	Paths        map[string]*Path       `protobuf:"bytes,6,rep,name=paths" json:"paths,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Components   *Components            `protobuf:"bytes,7,opt,name=components" json:"components,omitempty"`
	ExternalDocs *ExternalDocumentation `protobuf:"bytes,8,opt,name=external_docs,json=externalDocs" json:"external_docs,omitempty"`
}

func (m *OpenAPI) Reset()                    { *m = OpenAPI{} }
func (m *OpenAPI) String() string            { return proto.CompactTextString(m) }
func (*OpenAPI) ProtoMessage()               {}
func (*OpenAPI) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *OpenAPI) GetOpenapi() string {
	if m != nil {
		return m.Openapi
	}
	return ""
}

func (m *OpenAPI) GetInfo() *Info {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *OpenAPI) GetServers() []*Server {
	if m != nil {
		return m.Servers
	}
	return nil
}

func (m *OpenAPI) GetTags() []*Tag {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *OpenAPI) GetPaths() map[string]*Path {
	if m != nil {
		return m.Paths
	}
	return nil
}

func (m *OpenAPI) GetComponents() *Components {
	if m != nil {
		return m.Components
	}
	return nil
}

func (m *OpenAPI) GetExternalDocs() *ExternalDocumentation {
	if m != nil {
		return m.ExternalDocs
	}
	return nil
}

type Info struct {
	Title          string   `protobuf:"bytes,1,opt,name=title" json:"title,omitempty"`
	Description    string   `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
	TermsOfService string   `protobuf:"bytes,3,opt,name=terms_of_service,json=termsOfService" json:"terms_of_service,omitempty"`
	Contact        *Contact `protobuf:"bytes,4,opt,name=contact" json:"contact,omitempty"`
	License        *License `protobuf:"bytes,5,opt,name=license" json:"license,omitempty"`
	Version        string   `protobuf:"bytes,6,opt,name=version" json:"version,omitempty"`
}

func (m *Info) Reset()                    { *m = Info{} }
func (m *Info) String() string            { return proto.CompactTextString(m) }
func (*Info) ProtoMessage()               {}
func (*Info) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *Info) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Info) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Info) GetTermsOfService() string {
	if m != nil {
		return m.TermsOfService
	}
	return ""
}

func (m *Info) GetContact() *Contact {
	if m != nil {
		return m.Contact
	}
	return nil
}

func (m *Info) GetLicense() *License {
	if m != nil {
		return m.License
	}
	return nil
}

func (m *Info) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type Contact struct {
	Name  string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Url   string `protobuf:"bytes,2,opt,name=url" json:"url,omitempty"`
	Email string `protobuf:"bytes,3,opt,name=email" json:"email,omitempty"`
}

func (m *Contact) Reset()                    { *m = Contact{} }
func (m *Contact) String() string            { return proto.CompactTextString(m) }
func (*Contact) ProtoMessage()               {}
func (*Contact) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *Contact) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Contact) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Contact) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type License struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Url  string `protobuf:"bytes,2,opt,name=url" json:"url,omitempty"`
}

func (m *License) Reset()                    { *m = License{} }
func (m *License) String() string            { return proto.CompactTextString(m) }
func (*License) ProtoMessage()               {}
func (*License) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *License) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *License) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type Server struct {
	Url         string                     `protobuf:"bytes,1,opt,name=url" json:"url,omitempty"`
	Description string                     `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
	Variables   map[string]*ServerVariable `protobuf:"bytes,3,rep,name=variables" json:"variables,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *Server) Reset()                    { *m = Server{} }
func (m *Server) String() string            { return proto.CompactTextString(m) }
func (*Server) ProtoMessage()               {}
func (*Server) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

func (m *Server) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Server) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Server) GetVariables() map[string]*ServerVariable {
	if m != nil {
		return m.Variables
	}
	return nil
}

type ServerVariable struct {
	Enum        []string `protobuf:"bytes,1,rep,name=enum" json:"enum,omitempty"`
	Default     string   `protobuf:"bytes,2,opt,name=default" json:"default,omitempty"`
	Description string   `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
}

func (m *ServerVariable) Reset()                    { *m = ServerVariable{} }
func (m *ServerVariable) String() string            { return proto.CompactTextString(m) }
func (*ServerVariable) ProtoMessage()               {}
func (*ServerVariable) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

func (m *ServerVariable) GetEnum() []string {
	if m != nil {
		return m.Enum
	}
	return nil
}

func (m *ServerVariable) GetDefault() string {
	if m != nil {
		return m.Default
	}
	return ""
}

func (m *ServerVariable) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type Tag struct {
	Name         string                 `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Description  string                 `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
	ExternalDocs *ExternalDocumentation `protobuf:"bytes,3,opt,name=external_docs,json=externalDocs" json:"external_docs,omitempty"`
}

func (m *Tag) Reset()                    { *m = Tag{} }
func (m *Tag) String() string            { return proto.CompactTextString(m) }
func (*Tag) ProtoMessage()               {}
func (*Tag) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{6} }

func (m *Tag) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Tag) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Tag) GetExternalDocs() *ExternalDocumentation {
	if m != nil {
		return m.ExternalDocs
	}
	return nil
}

type ExternalDocumentation struct {
	Url         string `protobuf:"bytes,1,opt,name=url" json:"url,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
}

func (m *ExternalDocumentation) Reset()                    { *m = ExternalDocumentation{} }
func (m *ExternalDocumentation) String() string            { return proto.CompactTextString(m) }
func (*ExternalDocumentation) ProtoMessage()               {}
func (*ExternalDocumentation) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{7} }

func (m *ExternalDocumentation) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *ExternalDocumentation) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type Path struct {
	Summary     string     `protobuf:"bytes,1,opt,name=summary" json:"summary,omitempty"`
	Description string     `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
	Delete      *Operation `protobuf:"bytes,3,opt,name=delete" json:"delete,omitempty"`
	Get         *Operation `protobuf:"bytes,4,opt,name=get" json:"get,omitempty"`
	Head        *Operation `protobuf:"bytes,5,opt,name=head" json:"head,omitempty"`
	Options     *Operation `protobuf:"bytes,6,opt,name=options" json:"options,omitempty"`
	Patch       *Operation `protobuf:"bytes,7,opt,name=patch" json:"patch,omitempty"`
	Post        *Operation `protobuf:"bytes,8,opt,name=post" json:"post,omitempty"`
	Put         *Operation `protobuf:"bytes,9,opt,name=put" json:"put,omitempty"`
	Trace       *Operation `protobuf:"bytes,10,opt,name=trace" json:"trace,omitempty"`
}

func (m *Path) Reset()                    { *m = Path{} }
func (m *Path) String() string            { return proto.CompactTextString(m) }
func (*Path) ProtoMessage()               {}
func (*Path) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{8} }

func (m *Path) GetSummary() string {
	if m != nil {
		return m.Summary
	}
	return ""
}

func (m *Path) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Path) GetDelete() *Operation {
	if m != nil {
		return m.Delete
	}
	return nil
}

func (m *Path) GetGet() *Operation {
	if m != nil {
		return m.Get
	}
	return nil
}

func (m *Path) GetHead() *Operation {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *Path) GetOptions() *Operation {
	if m != nil {
		return m.Options
	}
	return nil
}

func (m *Path) GetPatch() *Operation {
	if m != nil {
		return m.Patch
	}
	return nil
}

func (m *Path) GetPost() *Operation {
	if m != nil {
		return m.Post
	}
	return nil
}

func (m *Path) GetPut() *Operation {
	if m != nil {
		return m.Put
	}
	return nil
}

func (m *Path) GetTrace() *Operation {
	if m != nil {
		return m.Trace
	}
	return nil
}

type Operation struct {
	Tags         []string               `protobuf:"bytes,1,rep,name=tags" json:"tags,omitempty"`
	Summary      string                 `protobuf:"bytes,2,opt,name=summary" json:"summary,omitempty"`
	Description  string                 `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
	ExternalDocs *ExternalDocumentation `protobuf:"bytes,4,opt,name=external_docs,json=externalDocs" json:"external_docs,omitempty"`
	OperationId  string                 `protobuf:"bytes,5,opt,name=operation_id,json=operationId" json:"operation_id,omitempty"`
	Responses    map[string]*Response   `protobuf:"bytes,8,rep,name=responses" json:"responses,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Deprecated   bool                   `protobuf:"varint,10,opt,name=deprecated" json:"deprecated,omitempty"`
}

func (m *Operation) Reset()                    { *m = Operation{} }
func (m *Operation) String() string            { return proto.CompactTextString(m) }
func (*Operation) ProtoMessage()               {}
func (*Operation) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{9} }

func (m *Operation) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *Operation) GetSummary() string {
	if m != nil {
		return m.Summary
	}
	return ""
}

func (m *Operation) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Operation) GetExternalDocs() *ExternalDocumentation {
	if m != nil {
		return m.ExternalDocs
	}
	return nil
}

func (m *Operation) GetOperationId() string {
	if m != nil {
		return m.OperationId
	}
	return ""
}

func (m *Operation) GetResponses() map[string]*Response {
	if m != nil {
		return m.Responses
	}
	return nil
}

func (m *Operation) GetDeprecated() bool {
	if m != nil {
		return m.Deprecated
	}
	return false
}

type Components struct {
	Schemas map[string]*Schema `protobuf:"bytes,1,rep,name=schemas" json:"schemas,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *Components) Reset()                    { *m = Components{} }
func (m *Components) String() string            { return proto.CompactTextString(m) }
func (*Components) ProtoMessage()               {}
func (*Components) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{10} }

func (m *Components) GetSchemas() map[string]*Schema {
	if m != nil {
		return m.Schemas
	}
	return nil
}

type Schema struct {
	Description string             `protobuf:"bytes,1,opt,name=description" json:"description,omitempty"`
	Type        string             `protobuf:"bytes,2,opt,name=type" json:"type,omitempty"`
	Properties  map[string]*Schema `protobuf:"bytes,3,rep,name=properties" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Required    []string           `protobuf:"bytes,4,rep,name=required" json:"required,omitempty"`
	Format      string             `protobuf:"bytes,5,opt,name=format" json:"format,omitempty"`
	Ref         string             `protobuf:"bytes,6,opt,name=ref" json:"ref,omitempty"`
}

func (m *Schema) Reset()                    { *m = Schema{} }
func (m *Schema) String() string            { return proto.CompactTextString(m) }
func (*Schema) ProtoMessage()               {}
func (*Schema) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{11} }

func (m *Schema) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Schema) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Schema) GetProperties() map[string]*Schema {
	if m != nil {
		return m.Properties
	}
	return nil
}

func (m *Schema) GetRequired() []string {
	if m != nil {
		return m.Required
	}
	return nil
}

func (m *Schema) GetFormat() string {
	if m != nil {
		return m.Format
	}
	return ""
}

func (m *Schema) GetRef() string {
	if m != nil {
		return m.Ref
	}
	return ""
}

type Response struct {
	Description string                `protobuf:"bytes,1,opt,name=description" json:"description,omitempty"`
	Content     map[string]*MediaType `protobuf:"bytes,3,rep,name=content" json:"content,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{12} }

func (m *Response) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Response) GetContent() map[string]*MediaType {
	if m != nil {
		return m.Content
	}
	return nil
}

type MediaType struct {
	Schema *Schema `protobuf:"bytes,1,opt,name=schema" json:"schema,omitempty"`
}

func (m *MediaType) Reset()                    { *m = MediaType{} }
func (m *MediaType) String() string            { return proto.CompactTextString(m) }
func (*MediaType) ProtoMessage()               {}
func (*MediaType) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{13} }

func (m *MediaType) GetSchema() *Schema {
	if m != nil {
		return m.Schema
	}
	return nil
}

func init() {
	proto.RegisterType((*OpenAPI)(nil), "com.pseudomuto.protoc_gen_twagger.options.OpenAPI")
	proto.RegisterType((*Info)(nil), "com.pseudomuto.protoc_gen_twagger.options.Info")
	proto.RegisterType((*Contact)(nil), "com.pseudomuto.protoc_gen_twagger.options.Contact")
	proto.RegisterType((*License)(nil), "com.pseudomuto.protoc_gen_twagger.options.License")
	proto.RegisterType((*Server)(nil), "com.pseudomuto.protoc_gen_twagger.options.Server")
	proto.RegisterType((*ServerVariable)(nil), "com.pseudomuto.protoc_gen_twagger.options.ServerVariable")
	proto.RegisterType((*Tag)(nil), "com.pseudomuto.protoc_gen_twagger.options.Tag")
	proto.RegisterType((*ExternalDocumentation)(nil), "com.pseudomuto.protoc_gen_twagger.options.ExternalDocumentation")
	proto.RegisterType((*Path)(nil), "com.pseudomuto.protoc_gen_twagger.options.Path")
	proto.RegisterType((*Operation)(nil), "com.pseudomuto.protoc_gen_twagger.options.Operation")
	proto.RegisterType((*Components)(nil), "com.pseudomuto.protoc_gen_twagger.options.Components")
	proto.RegisterType((*Schema)(nil), "com.pseudomuto.protoc_gen_twagger.options.Schema")
	proto.RegisterType((*Response)(nil), "com.pseudomuto.protoc_gen_twagger.options.Response")
	proto.RegisterType((*MediaType)(nil), "com.pseudomuto.protoc_gen_twagger.options.MediaType")
}

func init() { proto.RegisterFile("swagger.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 1052 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xb4, 0x97, 0xdd, 0x6e, 0xe3, 0x44,
	0x14, 0xc7, 0x95, 0xd8, 0x49, 0xec, 0x93, 0xb4, 0x58, 0x23, 0x40, 0x56, 0x2e, 0x50, 0xf1, 0x55,
	0xb9, 0xf1, 0x8a, 0x2e, 0x48, 0x80, 0x84, 0xb4, 0xdb, 0x52, 0xa0, 0xd9, 0x42, 0x2b, 0xb7, 0x70,
	0xb1, 0x42, 0x84, 0x59, 0xfb, 0x24, 0xb5, 0x88, 0x3f, 0x76, 0x3c, 0xee, 0xd2, 0x17, 0xe0, 0x0d,
	0xb8, 0x43, 0x5c, 0xf0, 0x56, 0xfb, 0x28, 0x5c, 0x20, 0xa1, 0xf9, 0x4a, 0x93, 0x36, 0x62, 0x63,
	0xaf, 0x7a, 0x37, 0x1f, 0x9e, 0xdf, 0xc9, 0xf9, 0xcf, 0x39, 0x67, 0x4e, 0x60, 0xa7, 0x7a, 0x45,
	0xe7, 0x73, 0x64, 0x61, 0xc9, 0x0a, 0x5e, 0x90, 0x8f, 0xe2, 0x22, 0x0b, 0xcb, 0x0a, 0xeb, 0xa4,
	0xc8, 0x6a, 0x5e, 0xa8, 0xd5, 0x78, 0x3a, 0xc7, 0x7c, 0xca, 0xf5, 0x87, 0x45, 0xc9, 0xd3, 0x22,
	0xaf, 0x82, 0x7f, 0x6d, 0x18, 0x9c, 0x95, 0x98, 0x3f, 0x3d, 0x3f, 0x21, 0x3e, 0x0c, 0x8a, 0x12,
	0x73, 0x5a, 0xa6, 0x7e, 0x67, 0xaf, 0xb3, 0xef, 0x46, 0x66, 0x4a, 0x8e, 0xc0, 0x4e, 0xf3, 0x59,
	0xe1, 0x77, 0xf7, 0x3a, 0xfb, 0xc3, 0x83, 0x47, 0xe1, 0xd6, 0xfc, 0xf0, 0x24, 0x9f, 0x15, 0x91,
	0x3c, 0x4c, 0x9e, 0xc1, 0xa0, 0x42, 0x76, 0x8d, 0xac, 0xf2, 0xed, 0x3d, 0x6b, 0x7f, 0x78, 0xf0,
	0x71, 0x03, 0xce, 0x85, 0x3c, 0x19, 0x19, 0x02, 0x39, 0x04, 0x9b, 0xd3, 0x79, 0xe5, 0xf7, 0x24,
	0x29, 0x6c, 0x40, 0xba, 0xa4, 0xf3, 0x48, 0x9e, 0x25, 0x17, 0xd0, 0x2b, 0x29, 0xbf, 0xaa, 0xfc,
	0xbe, 0x84, 0x7c, 0xd9, 0x00, 0xa2, 0x25, 0x0b, 0xcf, 0xc5, 0xf9, 0xe3, 0x9c, 0xb3, 0x9b, 0x48,
	0xb1, 0xc8, 0x0f, 0x00, 0x71, 0x91, 0x95, 0x45, 0x8e, 0x39, 0xaf, 0xfc, 0x81, 0x14, 0xec, 0xd3,
	0x06, 0xe4, 0xa3, 0xe5, 0xe1, 0x68, 0x05, 0x44, 0x10, 0x76, 0xf0, 0x37, 0x8e, 0x2c, 0xa7, 0x8b,
	0x69, 0x52, 0xc4, 0x95, 0xef, 0x48, 0xf2, 0x93, 0x06, 0xe4, 0x63, 0x7d, 0xfe, 0xab, 0x22, 0xae,
	0x33, 0xcc, 0x39, 0x15, 0xcb, 0xd1, 0x08, 0x6f, 0x97, 0xab, 0x71, 0x0a, 0x70, 0xeb, 0x12, 0xf1,
	0xc0, 0xfa, 0x15, 0x6f, 0x74, 0x30, 0x88, 0x21, 0x39, 0x86, 0xde, 0x35, 0x5d, 0xd4, 0xd8, 0x22,
	0x12, 0x04, 0x37, 0x52, 0xa7, 0xbf, 0xe8, 0x7e, 0xd6, 0x99, 0xd8, 0x8e, 0xe5, 0xd9, 0xc1, 0x5f,
	0x5d, 0xb0, 0x45, 0x8c, 0x90, 0x77, 0xa1, 0xc7, 0x53, 0xbe, 0x40, 0x6d, 0x4d, 0x4d, 0xc8, 0x1e,
	0x0c, 0x13, 0xac, 0x62, 0x96, 0x4a, 0x88, 0xb4, 0xea, 0x46, 0xab, 0x4b, 0x64, 0x1f, 0x3c, 0x8e,
	0x2c, 0xab, 0xa6, 0xc5, 0x6c, 0x2a, 0x82, 0x23, 0x8d, 0xd1, 0xb7, 0xe4, 0x67, 0xbb, 0x72, 0xfd,
	0x6c, 0x76, 0xa1, 0x56, 0xc9, 0x29, 0x0c, 0xe2, 0x22, 0xe7, 0x34, 0xe6, 0xbe, 0x2d, 0x7f, 0xfd,
	0x41, 0xa3, 0x6b, 0x91, 0x27, 0x23, 0x83, 0x10, 0xb4, 0x45, 0x1a, 0x63, 0x5e, 0xa1, 0xdf, 0x6b,
	0x4c, 0x3b, 0x55, 0x27, 0x23, 0x83, 0x10, 0xa9, 0x27, 0xc2, 0x5a, 0xf8, 0xd8, 0x57, 0xa9, 0xa7,
	0xa7, 0xc1, 0x31, 0x0c, 0xb4, 0x6d, 0x42, 0xc0, 0xce, 0x69, 0x66, 0x14, 0x92, 0x63, 0x71, 0x45,
	0x35, 0x5b, 0x68, 0x61, 0xc4, 0x50, 0x08, 0x89, 0x19, 0x4d, 0x17, 0x5a, 0x05, 0x35, 0x09, 0x1e,
	0xc1, 0x40, 0x1b, 0xdd, 0x0e, 0x13, 0xfc, 0xd1, 0x85, 0xbe, 0x4a, 0x3a, 0xb3, 0xd9, 0xb9, 0xb5,
	0xf1, 0xe6, 0x6b, 0xf9, 0x19, 0xdc, 0x6b, 0xca, 0x52, 0xfa, 0x62, 0x81, 0x95, 0x6f, 0xc9, 0xfc,
	0x7a, 0xd2, 0x38, 0xdd, 0xc3, 0x1f, 0x0d, 0x42, 0xa5, 0xd8, 0x2d, 0x72, 0xfc, 0x0a, 0x76, 0xd7,
	0x37, 0x37, 0x04, 0xeb, 0xd9, 0x7a, 0xb0, 0x7e, 0xde, 0xd8, 0xbe, 0xb1, 0xb0, 0x12, 0xb6, 0xc1,
	0x2f, 0xb0, 0xbb, 0xbe, 0x29, 0xf4, 0xc4, 0xbc, 0xce, 0xfc, 0xce, 0x9e, 0x25, 0xf4, 0x14, 0x63,
	0x71, 0x9f, 0x09, 0xce, 0x68, 0xbd, 0xe0, 0x5a, 0x1c, 0x33, 0xbd, 0x2b, 0x9d, 0x75, 0x4f, 0xba,
	0xe0, 0xef, 0x0e, 0x58, 0x97, 0x74, 0xbe, 0xf1, 0x9e, 0xde, 0x2c, 0xfc, 0xbd, 0x42, 0x61, 0x3d,
	0x44, 0xa1, 0x08, 0x9e, 0xc1, 0x7b, 0x1b, 0x3f, 0x6b, 0x13, 0x2c, 0xc1, 0x9f, 0x3d, 0xb0, 0x45,
	0x79, 0x10, 0xb2, 0x55, 0x75, 0x96, 0x51, 0x66, 0xee, 0xd1, 0x4c, 0xb7, 0x70, 0xfc, 0x14, 0xfa,
	0x09, 0x2e, 0x90, 0xa3, 0xf6, 0xf8, 0x93, 0x66, 0xe5, 0x9c, 0x29, 0x2f, 0x35, 0x83, 0x7c, 0x0d,
	0xd6, 0x1c, 0x4d, 0xa1, 0x68, 0x87, 0x12, 0x00, 0xf2, 0x2d, 0xd8, 0x57, 0x48, 0x13, 0x5d, 0x23,
	0xda, 0x81, 0x24, 0x81, 0x7c, 0x2f, 0x5e, 0x67, 0xb9, 0x25, 0x4b, 0x44, 0x5b, 0x98, 0x81, 0x90,
	0x89, 0x7c, 0xfd, 0xe2, 0x2b, 0xfd, 0x46, 0xb5, 0xa3, 0x29, 0x84, 0xf0, 0xb2, 0x2c, 0x2a, 0xae,
	0x1f, 0xa5, 0x96, 0x5e, 0x0a, 0x82, 0xd0, 0xbd, 0xac, 0xb9, 0xef, 0xbe, 0x8d, 0xee, 0x65, 0xcd,
	0x85, 0x77, 0x9c, 0xd1, 0x18, 0x7d, 0x78, 0x1b, 0xef, 0x24, 0x22, 0xf8, 0xc7, 0x02, 0x77, 0xb9,
	0x28, 0xd2, 0x52, 0x76, 0x1e, 0x3a, 0xdd, 0x65, 0x27, 0xb1, 0x12, 0xb7, 0xdd, 0xff, 0x8d, 0x5b,
	0x6b, 0x8b, 0x84, 0xb5, 0x1f, 0x22, 0x61, 0xc9, 0x87, 0x30, 0x2a, 0x8c, 0x0f, 0xd3, 0x54, 0x05,
	0xa4, 0x1b, 0x0d, 0x97, 0x6b, 0x27, 0x09, 0xa1, 0xe0, 0x32, 0xac, 0xca, 0x22, 0xaf, 0x50, 0xf4,
	0x17, 0xa2, 0x66, 0x1f, 0xb5, 0xd1, 0x2d, 0x8c, 0x0c, 0x45, 0x97, 0xed, 0x25, 0x95, 0x7c, 0x00,
	0x90, 0x60, 0xc9, 0x30, 0xa6, 0x1c, 0x13, 0x79, 0x37, 0x4e, 0xb4, 0xb2, 0x32, 0x7e, 0x09, 0xbb,
	0xeb, 0x87, 0x37, 0x94, 0xf5, 0x93, 0xf5, 0xb2, 0xfe, 0xb8, 0xc1, 0x4f, 0x34, 0xec, 0xf5, 0x3e,
	0xa4, 0xef, 0x0d, 0x26, 0xb6, 0x33, 0xf0, 0x9c, 0x89, 0xed, 0xb8, 0x1e, 0x4c, 0x6c, 0x67, 0xe8,
	0x8d, 0x26, 0xb6, 0x33, 0xf2, 0x76, 0x82, 0xd7, 0x1d, 0x80, 0xdb, 0x96, 0x8c, 0xfc, 0x04, 0x83,
	0x2a, 0xbe, 0xc2, 0x8c, 0xaa, 0xfb, 0x1f, 0x1e, 0x1c, 0xb6, 0x6a, 0xed, 0xc2, 0x0b, 0x05, 0x51,
	0xfa, 0x18, 0xe4, 0x38, 0x83, 0xd1, 0xea, 0xc6, 0x06, 0xdf, 0xbf, 0x59, 0xf7, 0xbd, 0x51, 0x07,
	0x2d, 0xc9, 0xab, 0x4f, 0xd9, 0x6b, 0xf1, 0xc4, 0xcb, 0xd5, 0xbb, 0x61, 0xda, 0xb9, 0x1f, 0xa6,
	0x22, 0xec, 0x6f, 0x4a, 0xd4, 0xf1, 0x2d, 0xc7, 0x84, 0x02, 0x94, 0x4c, 0x44, 0x10, 0x4f, 0x97,
	0xaf, 0xfc, 0xd3, 0xc6, 0x3f, 0x29, 0x3c, 0x5f, 0x32, 0x94, 0x1e, 0x2b, 0x50, 0x32, 0x06, 0x87,
	0xe1, 0xcb, 0x3a, 0x65, 0x98, 0xc8, 0x7f, 0x0d, 0x6e, 0xb4, 0x9c, 0x93, 0xf7, 0xa1, 0x3f, 0x2b,
	0x58, 0x46, 0xb9, 0x0e, 0x66, 0x3d, 0x13, 0xb2, 0x31, 0x9c, 0xe9, 0x46, 0x4a, 0x0c, 0xc7, 0x25,
	0xbc, 0x73, 0xc7, 0xc8, 0x43, 0x6b, 0xfb, 0x7b, 0x17, 0x1c, 0x13, 0x6d, 0x5b, 0xa8, 0xfb, 0x5c,
	0xf5, 0xa6, 0x98, 0xf3, 0x16, 0xcd, 0x92, 0xb1, 0x23, 0x9b, 0x54, 0xcc, 0xb9, 0x8e, 0x2a, 0x0d,
	0x1c, 0x97, 0x30, 0x5a, 0xdd, 0xd8, 0xe0, 0xf9, 0x64, 0xdd, 0xf3, 0x26, 0xc5, 0xf2, 0x3b, 0x4c,
	0x52, 0x7a, 0x79, 0x53, 0xde, 0x49, 0xa9, 0xae, 0x67, 0x4d, 0x6c, 0xc7, 0xf6, 0x7a, 0xc1, 0x15,
	0xb8, 0xcb, 0x6f, 0xc8, 0x09, 0xf4, 0x55, 0xac, 0x4b, 0xeb, 0xad, 0x34, 0xd6, 0x80, 0xa5, 0x0d,
	0xcb, 0xb3, 0x95, 0xa5, 0x43, 0xf7, 0xb9, 0x79, 0xdb, 0x5e, 0xf4, 0x25, 0xe7, 0xf1, 0x7f, 0x01,
	0x00, 0x00, 0xff, 0xff, 0x36, 0x7d, 0x69, 0x51, 0x18, 0x0f, 0x00, 0x00,
}
